### PR TITLE
Add support for annotation groups

### PR DESCRIPTION
**Pull request by ldriscoll**
Rosetta Annotations, are all annotated with `@RosettaAnnotation`; other libraries do this for good housekeeping.  I have made a change here so that our style can have:
`additionalJsonAnnotations = { RosettaAnnotation.class }`

so that when Rosetta adds more annotations we don't need to add them to the style. 

Hope it makes sense

### CODE REVIEW

**Comment by ldriscoll** [comment]
@jhaber

**Comment by jhaber** [comment]
I think this a very deep rabbit hole. Having an intermediary class for deserialization means that immutables will never play nice with Jackson

**Comment by elucash** [comment]
@jhaber it is so true. In fact we now use original class for writing json, and synthetic one only for reading. 
And still have #185 and alike. Jackson on it's own have couple of inconsistencies (like handling of `JsonValue` with regards to type mapping etc).
So while I'm reviewing this pull request, we're also open to suggestions how to radically improve the situation @ldriscoll  @jhaber have any idea?

**Comment by jhaber** [comment]
I'm not very familiar with the generated code, is it not feasible to deserialize directly into the immutable type? If an intermediary type is necessary, you could try making it a POJO that extends the interface/abstract class, that way it inherits any annotations and extra methods

**Comment by jhaber** [comment]
I'm not very familiar with the generated code, is it not feasible to deserialize directly into the immutable type? If an intermediary type is necessary, you could try making it a POJO that extends the interface/abstract class, that way it inherits any annotations and extra methods

**Comment by ldriscoll** [comment]
I think there would need to be a json deserializer that constructed one from a builder, and then called .build().  We'd still need for the annotations to be passed down into the immutable object though.

**Comment by ldriscoll** [comment]
I actually have an idea around this, I might give it a go.

**Comment by ldriscoll** [comment]
ok, I have a good working version of this now, but I'm still cleaning it up, it'll mean we can get rid of the additional json annotations and such.  I'm going to spend some time with the family, if you'd like to take a look the code is here: https://github.com/ldriscoll/immutables/tree/json_extend

**Comment by ldriscoll** [comment]
nope, going to have to leave the additional annotations there, because jackson, and friends, don't like not standard getters, which immutables annotates with `@JsonProperty` even when they are not in the parent class.  My feeling is that if main class is like this: https://github.com/immutables/immutables/blob/master/value-fixture/src/org/immutables/fixture/jackson/SampleJacksonMapped.java

Then it's the user's fault that it won't serialise to json, but currently Immutables puts `@JsonProperty` on the immutable's getters, so it serialises.

If you want to break that 'feature' we could get rid of ALL of the json annotation passing.

**Comment by elucash** [comment]
Thank you for the work! I'll merge those things now, but it will undergone some changes. Now I would take some deep thinking on how we could make all this working together (including #206).
Essentially, you've, probably, pushed this in the right direction, we just need all currently supported case working, including newly reported stuff.

**Pull request merged**
