### PR TITLE
Support MongoDB 4.0 #830

### PR DESCRIPTION
**Pull request by before**

### CODE REVIEW

**Comment by before** [comment]
@elucash do you know what is missing to get the test cases running?

**Comment by elucash** [comment]
There's a switch to run testsuites against local mongo

```
$ mvn test -DargLine="-Dmongo=mongodb://localhost"
```

@asereda-gs just checking if there are any known issues about #830 ?

**Comment by elucash** [comment]
anyway, if we cannot get the fix, it's should be not so hard to
1. run test suites against mongodb 4
2. override driver dependency version alongside using 'mongo' module (i.e. not rely on the driver version specified in `org.immutables:mongo`)

**Comment by asereda-gs** [comment]
I did run immutables tests locally with `-DargLine="-Dmongo=mongodb://localhost"`.
They pass for `4.0.2` and `4.1.2` (docker image).

**Comment by before** [comment]
@elucash and @asereda-gs thank you for the hints. It seems to work fine when using the 3.8.1 driver locally. I'm fine at the moment.

**Comment by asereda-gs** [comment]
@before if your issue has been solved can you pls close this PR ?

**Pull request closed without merging**
