### PR TITLE
Travis CI: add openjdk11

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by elucash** [comment]
@asereda-gs is this a failed experiment (and addressed by other means) which can be closed now?

**Comment by MysterAitch** [comment]
> 
> 
> @asereda-gs is this a failed experiment (and addressed by other means) which can be closed now?


Additionally, are you aware that travis-ci.org is closing down in December 2020?

**Comment by sullis** [comment]
Closing this PR. I recommend migrating this project from TravisCI to GitHub Actions CI.

**Comment by sullis** [comment]
GitHub Actions: https://github.com/immutables/immutables/pull/1244

**Comment by elucash** [comment]
nope, not aware, gosh... time flies by. Hope #1244 is the way

**Pull request closed without merging**
