### PR TITLE
fix for classes with underscores

### PR DESCRIPTION
**Pull request by The-Alchemist**
Fix for https://github.com/immutables/immutables/issues/154

### CODE REVIEW

**Comment by The-Alchemist** [comment]
Also includes a test that fails for classes that _start_ with an underscore.  That's why the build is failing.

**Comment by The-Alchemist** [comment]
Also includes a test that fails for classes that _start_ with an underscore.  Wasn't sure how to fix that one at the moment.

**Comment by elucash** [comment]
Thank you! I'll merge that! For the classes starting with the underscore we will, probably, leave them fully qualified in the generated source code. We try to read imports from the source only as last resort if we cannot resolve types.

**Comment by The-Alchemist** [comment]
Thanks for merging!  Any ideas on when the next release that includes this fix will be?

**Comment by elucash** [comment]
We will release beta to central after the weekend, and 2.1 release is expected then in a week or two. In a meantime you can try snapshots available from sonatype oss repo (same as described in #150). Thanks!

**Pull request merged**
