### PR TITLE
Add style which allows developer to configure how validation is performed, including new option to disable null checks, and another option to use Java Validation API

### PR DESCRIPTION
**Pull request by garakelian**
@elucash, this is a very rough, untested, first cut at disabling required fields, per our discussion in #496. Just wanted you to take a look at it, and let me know if I'm on the right path.

The intent of this PR is disable checks for "required" attributes, such that:
1. You don't have to add "@Nullable" to every field
2. You don't have to provide default values for primitives if you are content with 0 and false.

### CODE REVIEW

**Comment by garakelian** [comment]
@elucash, I tested this locally, and it works well.  When this style is enabled, ValueAttribute.isMandatory() always returns false, which results in the initBits stuff never getting generated.

**Comment by garakelian** [comment]
@elucash - So, I updated this PR to add support for Java Validation API. There are now 3 options for validation: (1) turn off, e.g. the original intent of this PR (2) simple, which is what the project currently supports, and (3) use Java Validation API to verify bean, replacing current approach.

**Comment by elucash** [comment]
@garakelian I very like your work, and how you've managed to get thru the stuff, the use of `isMandatory` perfectly matches the intent!

I do think that dedicated Validation API support is, probably, a bit redundant, you probably know about BYOM approach I outlined in #26. There's a problem with validator management: validator factory/validator creation is potentially CPU and memory expensive. When using BYOM, you can decide if you want a single static validator or a passed in request-/app-scoped instance. Putting aside performance concerns, I think it could be nice to have easy, switch-on Validation API support. But it seems wasteful to have it only for the experimentation reasons, switching to BYOM-like approach later.
My thumbs up for the initial disable-mandatory-check flag approach.
Validator instance handling is currently a stumbling block for me, convenience-oriented experimentation-only functionality is something we would like to avoid. If we can solve the validator instance handling somehow, there remaining suggestion would be to not use validation on a builder path, but rather use precondition checking phase (where we invoke checker methods, interning and canonicalization hooks), the reason is that validation should work consistently across all construction paths, not only via builder.

Let's keep in mind that we're also want to avoid introducing mandatory runtime dependencies, at least in the default module. What would I propose? We can create separate API module like `org.immutables:validation` and place mix-in there. The mix-in would have a single static validator created for straightforwardness. We can introduce a validation annotation in that module to auto-implement the mix-in as the alternative to inheriting it. Actual supporting annotation processing code would still be inside `value-processor` module, but we will have cleaner/optional runtime API which itself will have a dependency on `javax.validation` API

**Comment by garakelian** [comment]
@elucash Thanks for the feedback. I honestly had not read #26 before. After my first implementation, using `isMandatory`, I began to think about it some more and in a moment of inspiration, just made the change. I like that your framework's default behavior is to try to ensure a bean is properly constructed, and upon reflection, I thought I should do more than simply disable this feature. Thus, I added support Validation API.

With regards to the idea of a mix-in, let me say, I completely agree that we don't want to introduce any runtime dependencies, which is why I'm hesitant to agree to that approach. One of the coolest features of code generation within a Java annotation processor is that it has access to the classpath of the enclosing code!  When I first used Immutables, I was very impressed to see that you checked if Guava was on the classpath, and you modified the code generation appropriately. I'd like to do the same thing here if possible.

However, I understand your concern about initializing the ValidatorFactory multiple times. I'm less concerned however, with supporting generic implementations of "validation", because it's a complex issue, and because the Hibernate Validator is the reference implementation of the JSR. Spring uses it, issue #26 references it, etc. It's like Guava - widely used and well tested. If we really wanted to that later on, the BuilderValidationMethod is a enum, and we could add another option there.

So, how can we solve the multiple initializations? A simple approach would be to use a static field to hold a reference to the Validator. From the Hibernate Validator documentation (http://docs.jboss.org/hibernate/validator-backup/4.0.1/reference/en-US/html_single/): "A Validator instance is thread-safe and may be reused multiple times". This would be a trivial change.

Another approach, also not too difficult, would be to add a Style attribute to allow the developer to specify a class instance that would contain a static factory method, something like getValidatorFactory() that returns javax.validation.ValidatorFactory.

**Comment by elucash** [comment]
The usage of a static singleton is ok in general. The caveat is that there will be validator per each value class. This is a drastic improvement from having validators created over and over again for each value object instantiation but still can be suboptimal. This should be acceptable, though. (with a separate mix-in using static field, all inheriting objects are using that one instance)

The other thing which worries me is that validation should be executed thru all construction paths. You really should try to move the validation logic to the "centralized" place, where each object will go thru validation regardless if it was constructed using constructor or intented. Here's the points in the code involved:

* `ValueType.isUseValidation()` should return true early if jsr303 should be used.
*  There's validation sequence. Look for the following fragment:
```
[if type.useValidation]

  private static [type.generics.spaceAfter][type.typeImmutable.relative] validate([type.typeImmutable.relative] instance) {
[for vm in type.validationMethods]
  [if vm.normalize]
    instance = ([type.typeImmutable.relative]) instance.[vm.name]();
  [else]
    instance.[vm.name]();
  [/if]
[/for]
[if type.useSingletonOnly]
    return INSTANCE != null ? INSTANCE : instance;[-- may be null during initialization --]
[else if type.generateOrdinalValue]
    return ([type.typeImmutable.relative]) instance.domain.internOrdinal(new InternProxy(instance));
[else if type.useInterned]
  [if type.generateJdkOnly]
    [atNullable][type.typeImmutable.relative] interned = INTERNER.putIfAbsent(new InternProxy(instance), instance);
    return interned != null ? interned : instance;
  [else]
    return INTERNER.intern(new InternProxy(instance)).instance;
  [/if]
[else if type.useSingleton]
    return INSTANCE != null && INSTANCE.equalTo(instance) ? INSTANCE : instance;[-- may be null during initialization --]
[else]
    return instance;
[/if]
  }
[/if]
```
* The jsr303 fragment should be inserted into the very beginning of the validation routine, i.e. before `[for vm in type.validationMethods]`

Please, do not consider this nitpicking, I just want to align this functionality with existing features and overall design. I do really appreciate your efforts to make the library better! Thank you!

**Comment by garakelian** [comment]
@elucash Thanks again for the feedback. Good comments. I definitely didn't intend to leave out any code paths that could escape validation. I'll look for the validation sequence you suggested in the morning and update the PR. Happy to help here, thanks for your excellent library!

**Comment by Stephan202** [comment]
The changes now under discussion seem to assume that the default `Validator` (as acquired through `Validation.buildDefaultValidatorFactory().getValidator()`) will suffice. It's easy to envision a new feature request in the not-so-distant future asking for a custom `Validator` to be used. For example, a user may want to create a `Validator` instance in an environment in which no EL implementation is present (like in [HV-1131](https://hibernate.atlassian.net/browse/HV-1131)).

So it seems to me now is the time to figure out how to make this customizable. Since I also think statics should be avoided: how about some kind of "Immutables factory"? Sketch:

```java
MyDtoFactory factory = MyDtoFactory.create(someValidator);
SomeDtoType dto = factory.someDtoTypeBuilder()......build();
```

The idea here would be that:
1. `MyDtoFactory` would be generated. Its name is customizable, and it allows the construction of all immutables within the same "group", as configured using `@Style`.
2. `MyDtoFactory` would have one or more methods for each immutable type it knows about, corresponding to the creator and builder methods currently defined on the immutable types themselves.
3. `MyDtoFactory` is parametric on a `Validator`, allowing customization thereof. As a big extra plus, it obviates the need for a static `Validator` instance per immutable type; now there's just one instance for all types.

(Perhaps my proposal in point 1 is not possible due to the way annotation processing works, esp. in the context of incremental compilation... but I hope not. In that case there'd have to be one factory per immutable type, which is less nice.)

WDYT?

**Comment by garakelian** [comment]
@Stephan202 I agree that we'll eventually need a way to create a custom validator, but I don't think the best way to do that is using a singleton factory as you describe. First, it's tedious, as most projects will likely have lots of generated classes, and now you've got to create singletons for all of them, simply so you can pass the Validator factory to it.  Second, what about Jackson deserialization? Although Jackson supports deserialization through a builder, does it support a singleton builder?

I personally see this feature working the other way around. I think the builder should reach out (using a Style attribute described above), to get a static ValidatorFactory, which would enable a developer to cache/customize the creation anyway they see fit.

**Comment by garakelian** [comment]
@Stephan202 and @elucash - After some research, I don't think we need to do anything regarding the installation of custom JSR 303 validators. This is part of JSR303 itself.

This is code used to initialize the validator:
```
  private static final Validator validator = Validation.buildDefaultValidatorFactory().getValidator();
```

If you look at the code for Validation.buildDefaultValidatorFactory, you can see that it uses standard Java service discovery mechanisms to [find the implementation](http://grepcode.com/file/repo1.maven.org/maven2/javax.validation/validation-api/1.1.0.Final/javax/validation/ValidationProviderResolver.java#ValidationProviderResolver.getValidationProviders%28%29).

**Comment by elucash** [comment]
@Stephan202 as I'm concerned about custom validator creation or propagation, it should be handled in DYI manner in a way described in #26 using custom mix-in. The functionality here is similar to strong interning we provide: default or nothing. I'm against introducing fine-grained configuration to something that can be easily built on top. The only exception is simple out of the box experience for some standard (de-facto or de-jsr-ure). I'm planning to highlight how jsr303 can be integrated/configured in the javadoc for the new switch and the guide.

**Comment by elucash** [comment]
@garakelian merged, thank you! Let me muse a little on the annotation API itself before releasing. I have a couple of thought to confirm with you. I'll return to this in two (hope not more that this). Thank you!

**Pull request merged**
