### PR TITLE
Prevent Error-Prone `NumericEquality` warning

### PR DESCRIPTION
**Pull request by Stephan202**
In a1d3518d4851291103fd98a449fbbd8fded90579 triggering `NumericEquality`
warnings is prevented for optional numbers. This change tackles non-optional
`java.lang.Number` instances.

This relates to #570.

### CODE REVIEW

**Comment by Stephan202** [comment]
I checked that this change fixes the problem we've observed, but please do verify carefully. Note that this change also syncs the JavaDoc and code-level checks, so that's an extra plus.

**Comment by elucash** [comment]
Thank you for PR!
the change to `hasSimpleScalarElementType` seems mostly equivalent (Albeit it was initially designed for checking containers' element types). Can you please check if having `or v.enumType` along with primitive would be ok wrt error-prone, so we would still `==` enums.
Test value object can check enum attribute and list of enums, to see if we handle it correctly.

**Comment by Stephan202** [comment]
Will do :)

**Comment by elucash** [comment]
Superb! Thank you @Stephan202!

**Comment by Stephan202** [comment]
You're fast haha! I was still writing out some notes:
- I compared the code generated for the `ForEquals` class with what was generated at 657afa84a00d092d9f60ca622cd514b2ea8089c5 (i.e., just before your initial changes). Code-wise only the `BigDecimal` comparisons are changed, as required.
- In terms of Javadoc, there is now one place where it says enums are compared using an "An equals check" rather than a "A shallow reference equality check". I can fix that, but it'd mean that the if/else branches between the code and Javadoc don't line up, while for all intends and purposes the new text isn't wrong.

I do wonder: is there some way to validate/check the generated code, so that the regression I introduced could have been caught at build time?

**Comment by Stephan202** [comment]
Something else I noticed: even before 657afa84a00d092d9f60ca622cd514b2ea8089c5 (and now still; this is not a regression), the following code is generated:
```java
  public final ImmutableForEquals withMyOptinalRoundingMode(RoundingMode value) {
    @Nullable RoundingMode newValue = Preconditions.checkNotNull(value, "myOptinalRoundingMode");
    if (Objects.equal(this.myOptinalRoundingMode, newValue)) return this;
    return new ImmutableForEquals(
        this.myInt,
        this.myOptinalInt,
        this.myIntList,
        this.myBigDecimal,
        this.myOptinalBigDecimal,
        this.myBigDecimalList,
        this.myRoundingMode,
        newValue,
        this.myRoundingModeList,
        this.myObject,
        this.myOptinalObject,
        this.myObjectList);
  }
```

That `Objects.equal` could be replaced with an `==`. Maybe for another PR :). (But if you immediately see how to fix it: go ahead.)

**Comment by elucash** [comment]
> I do wonder: is there some way to validate/check the generated code, so that the regression I introduced could have been caught at build time?

I always wanted to avoid testing literal code output as it overspecifies code, making test very fragile for any changes including cosmetic ones. Usually, if you generate some code, the assertion could be the successful compilation, where otherwise it would not compile (sample code references generated elements and expect) or runtime test can prove that code is properly generated. It is more complicated with warnings, as actually stuff like google's compile-testing can help with that. But I've yet to actually use it, so now I inspect warnings as I run builds.'

> That Objects.equal could be replaced with an ==. Maybe for another PR :). (But if you immediately see how to fix it: go ahead.)

It can be different branch of `with` method generation. Will see

**Comment by Stephan202** [comment]
Thanks for the explanation :)

I think I found the place where to change the code, and I also noticed I made a typo ("Optinal"). WIll try to open an extra PR shortly.

**Comment by Stephan202** [comment]
For those reading along at home: the new PR is #584.

**Pull request merged**
