### PR TITLE
add support for making optionals handle null values.

### LINKED ISSUE #152: Switch from Optional.of to Optional.ofNullable
When we have `java.util.Optional<T>` fields, it would be nice that the `withX` methods could handle `null`, and use `java.util.Optional.ofNullable(x)` instead of `java.util.Optional.of(x)`

### PR DESCRIPTION
**Pull request by ldriscoll**
this fixes #152 @augustotravillio 
Let me know if I've missed something terrifying, or if I've done something out of the standard.  I've not used the generators before.

### CODE REVIEW

**Comment by augustotravillio** [comment]
Wow, that's great contribution, thank you, Luke! You were exceptionally good getting though our jungles! @elucash can you take a look and merge this, I will, probably, make some additions afterwards?

**Comment by elucash** [comment]
Looks comprehensive, thanks @ldriscoll!
@augustotravillio could you then check where we need to add `@Nullable` to the generated API

**Comment by aaylward** [comment]
:+1: thanks @ldriscoll

**Pull request merged**
