### PR TITLE
Java 17 compat.

### PR DESCRIPTION
**Pull request by SimY4**
Continuation of https://github.com/immutables/immutables/pull/1326

Looks like everything works on 17-ea also.

### CODE REVIEW

**Comment by elucash** [comment]
Thank you, will be looking at releasing this

**Comment by mikebell90** [comment]
@SimY4 confused about one thing - you include illegal access for java 16+, but java 17 will ignore that switch.... So immutables CANNOT need it ;)

**Comment by SimY4** [comment]
@mikebell90 it might break if we bump the JDK version to 17 release.

I was just lazy and worked around this problem with a single switch. The long term solution is to add a bunch of --add-opens for all specific JDK modules that the immutable generator requires.

**Comment by SimY4** [comment]
@mikebell90 FYI: https://github.com/immutables/immutables/pull/1337

**Pull request merged**
